### ISSUE TITLE
SharpBucket.Send syntax causes a WebException when calling GetDiffForPullRequest

### ISSUE THREAD

**Issue by L-E-son** [MitjaBezensek/SharpBucket#49]
Using GetDiffForPullRequest() throws two exceptions:

{`Data at the root level is invalid. Line 1, position 1."}	System.Exception {System.Xml.XmlException}`
and
`   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at SharpBucket.Authentication.Authenticate.GetResponse[T](String url, Method method, T body, IDictionary2 requestParameters)
   at SharpBucket.SharpBucket.Send[T](T body, Method method, String overrideUrl, IDictionary2 requestParameters)
   at SharpBucket.V2.EndPoints.RepositoriesEndPoint.GetDiffForPullRequest(String accountName, String repository, Int32 pullRequestId)
   at SharpBucket.V2.EndPoints.PullRequestResource.GetDiffForPullRequest()`

Not sure what's up, but I tried using curl with https://api.bitbucket.org/2.0/repositories/{username}/{repo_slug}/refs/branches/ and I can see that the branches have diffs (some empty, some not). There's some sort of edge case with the data being parsed, although I'm not quite sure what it is specifically.

**Comment by EbenZhang** [comment]
The GetDiff will recv a redirection from bitbucket server, but seems the server returns wrong url `https://bitbucket.org/!api/2.0/repositories/xxx` in where the `!api` should be `api`.

**Comment by MitjaBezensek** [comment]
Is there a public repo where this happens so that could reproduce it?

**Comment by EbenZhang** [comment]
should be quite easy to reproduce, just call that function.

**Comment by MitjaBezensek** [comment]
@EbenZhang Thanks, I managed to reproduce it.

I contacted bitbucket support to see if they might be able to help. Maybe we can use the correct url directly or something along those lines. I managed to get it working by doing some additional checking, but would prefer a cleaner solution since it seems kind of hacky and might break in the future.

**Comment by MitjaBezensek** [comment]
I fixed this and it is available in the 0.7.0 version of the package. I just uploaded it to NuGet.
